<?php

namespace Database\Seeders;

use App\Models\Farmer;
use Illuminate\Database\Seeder;

class FarmerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $farmers = [
            [
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'email' => 'juan.delacruz@example.com',
                'phone_number' => '09171234567',
                'address' => '123 Maharlika St.',
                'city' => 'Batangas City',
                'province' => 'Batangas',
                'postal_code' => '4200',
                'farm_description' => 'Multi-crop farm with modern irrigation',
                'farm_size_hectares' => 5.5,
                'status' => 'active',
                'registration_date' => '2024-01-01',
                'membership_renewal_date' => '2025-01-01',
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'email' => 'maria.santos@example.com',
                'phone_number' => '09182345678',
                'address' => '456 Rizal Ave.',
                'city' => 'San Pablo',
                'province' => 'Laguna',
                'postal_code' => '4000',
                'farm_description' => 'Organic vegetable farm',
                'farm_size_hectares' => 3.2,
                'status' => 'active',
                'registration_date' => '2024-01-15',
                'membership_renewal_date' => '2025-01-15',
            ],
            [
                'first_name' => 'Pedro',
                'last_name' => 'Reyes',
                'email' => 'pedro.reyes@example.com',
                'phone_number' => '09193456789',
                'address' => '789 Aguinaldo Highway',
                'city' => 'Tagaytay',
                'province' => 'Cavite',
                'postal_code' => '4120',
                'farm_description' => 'Highland vegetable farm',
                'farm_size_hectares' => 4.8,
                'status' => 'active',
                'registration_date' => '2024-02-01',
                'membership_renewal_date' => '2025-02-01',
            ],
            [
                'first_name' => 'Ana',
                'last_name' => 'Gonzales',
                'email' => 'ana.gonzales@example.com',
                'phone_number' => '09204567890',
                'address' => '101 National Highway',
                'city' => 'Calamba',
                'province' => 'Laguna',
                'postal_code' => '4027',
                'farm_description' => 'Riverside agricultural land',
                'farm_size_hectares' => 6.7,
                'status' => 'active',
                'registration_date' => '2024-02-15',
                'membership_renewal_date' => '2025-02-15',
            ],
            [
                'first_name' => 'Roberto',
                'last_name' => 'Tan',
                'email' => 'roberto.tan@example.com',
                'phone_number' => '09215678901',
                'address' => '202 Lipa-Alaminos Road',
                'city' => 'Lipa City',
                'province' => 'Batangas',
                'postal_code' => '4217',
                'farm_description' => 'Mixed crop farm',
                'farm_size_hectares' => 4.2,
                'status' => 'active',
                'registration_date' => '2024-03-01',
                'membership_renewal_date' => '2025-03-01',
            ],
            [
                'first_name' => 'Elena',
                'last_name' => 'Cruz',
                'email' => 'elena.cruz@example.com',
                'phone_number' => '09226789012',
                'address' => '303 Tagaytay-Silang Road',
                'city' => 'Silang',
                'province' => 'Cavite',
                'postal_code' => '4118',
                'farm_description' => 'Small-scale organic farm',
                'farm_size_hectares' => 3.8,
                'status' => 'active',
                'registration_date' => '2024-03-15',
                'membership_renewal_date' => '2025-03-15',
            ],
            [
                'first_name' => 'Carlos',
                'last_name' => 'Garcia',
                'email' => 'carlos.garcia@example.com',
                'phone_number' => '09237890123',
                'address' => '404 Tanauan-Talisay Road',
                'city' => 'Tanauan',
                'province' => 'Batangas',
                'postal_code' => '4232',
                'farm_description' => 'Traditional farming methods',
                'farm_size_hectares' => 5.1,
                'status' => 'active',
                'registration_date' => '2024-01-20',
                'membership_renewal_date' => '2025-01-20',
            ],
            [
                'first_name' => 'Isabella',
                'last_name' => 'Ramos',
                'email' => 'isabella.ramos@example.com',
                'phone_number' => '09248901234',
                'address' => '505 Alfonso Road',
                'city' => 'Alfonso',
                'province' => 'Cavite',
                'postal_code' => '4123',
                'farm_description' => 'Sustainable farming practices',
                'farm_size_hectares' => 2.9,
                'status' => 'active',
                'registration_date' => '2024-02-20',
                'membership_renewal_date' => '2025-02-20',
            ],
            [
                'first_name' => 'Miguel',
                'last_name' => 'Torres',
                'email' => 'miguel.torres@example.com',
                'phone_number' => '09259012345',
                'address' => '606 Laurel Highway',
                'city' => 'Laurel',
                'province' => 'Batangas',
                'postal_code' => '4221',
                'farm_description' => 'Mountain terraced farm',
                'farm_size_hectares' => 4.5,
                'status' => 'active',
                'registration_date' => '2024-03-05',
                'membership_renewal_date' => '2025-03-05',
            ],
            [
                'first_name' => 'Sofia',
                'last_name' => 'Mendoza',
                'email' => 'sofia.mendoza@example.com',
                'phone_number' => '09260123456',
                'address' => '707 Santa Rosa-Tagaytay Road',
                'city' => 'Santa Rosa',
                'province' => 'Laguna',
                'postal_code' => '4026',
                'farm_description' => 'Modern farming techniques',
                'farm_size_hectares' => 7.3,
                'status' => 'active',
                'registration_date' => '2024-03-10',
                'membership_renewal_date' => '2025-03-10',
            ],
        ];

        foreach ($farmers as $farmer) {
            Farmer::create($farmer);
        }
    }
} 